apiVersion: v1
kind: Service
metadata:
  name: spring-mysql-cicd
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 30007  # Optional: Specify a port in the range 30000-32767
  selector:
    app: spring-mysql-cicd

