apiVersion: apps/v1
kind: Deployment
metadata:
  name: raziel-ultimate-cicd
  labels:
    app: raziel-ultimate-cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: raziel-ultimate-cicd
  template:
    metadata:
      labels:
        app: raziel-ultimate-cicd
    spec:
      containers:
      - name: raziel-ultimate-cicd
        image: raziels/ultimate-cicd:26235006
        ports:
        - containerPort: 8080